### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by ariddell** [twiecki/pydata_docker_jupyterhub#1]
This is great. Thanks for making the Dockerfile.

Can conda install the same packages for Python 3?

**Comment by ariddell** [comment]
Actually, reading Stackoverflow it looks like you can't install both Python 2 and Python 3 conda packages globally. Shame!

**Comment by twiecki** [comment]
It would be pretty simple to just install miniconda3 instead (in fact, that's what I had initially but had to revert to python 2).

**Comment by ariddell** [comment]
I've got the notebooks working with Python 3 (no theano) here https://github.com/ariddell/pydata_docker_jupyterhub

It's  a shame there's no way to get everything installed at once.
