### ISSUE TITLE
ipywidgets failing

### ISSUE THREAD

**Issue by askerry** [twiecki/pydata_docker_jupyterhub#5]
Hi there,

I've been working off a fork of your jupyterhub setup (thanks!) and have found that ipywidgets do not work. I can import the module and create widgets, but they do not display (the widgets do display properly when running jupyterhub outside of docker). In the js console I can see that it 404s when trying to load 8000/user/test/nbextensions/widgets/notebook/js/extension.js. I am just wondering if you had the same experience. Trying to figure out if this an issue with my modifications or if there is some more global issue with using ipywidgets inside of docker. 

Thanks!

**Comment by twiecki** [comment]
It's possible that the ipython notebook is out-of-date. Maybe replacing that with jupyter-notebook does the trick? It's been a while from where I tried the updated version.

**Comment by askerry** [comment]
I ended up getting it to work sticking with pip installs rather than conda. Never figured out the exact issue though. Thanks!
